2015-02-19 08:35:03,244-__main__-INFO-Running PyArxiv
2015-02-19 08:35:03,244-__main__-ERROR-Failed to print 2.7 syntax
Traceback (most recent call last):
  File "D:\Dropbox\Python\Arxiv downloader\PyArxiv.py", line 20, in <module>
    print(boo)
NameError: name 'boo' is not defined
2015-02-19 08:35:11,650-__main__-INFO-Running PyArxiv
2015-02-20 07:13:14,008-__main__-INFO-Running PyArxiv
2015-02-20 19:19:38,065-__main__-INFO-Running PyArxiv
2015-02-21 10:28:58,845-__main__-INFO-Running PyArxiv
2015-02-23 10:30:17,236-__main__-INFO-Running PyArxiv
2015-02-24 10:42:57,873-__main__-INFO-Running PyArxiv
2015-02-24 19:29:46,206-__main__-INFO-Running PyArxiv
2015-02-25 09:38:36,665-__main__-INFO-Running PyArxiv
2015-02-25 23:23:43,723-__main__-INFO-Running PyArxiv
2015-02-27 08:41:19,416-__main__-INFO-Running PyArxiv
2015-02-27 08:46:16,205-__main__-INFO-Running PyArxiv
2015-02-28 10:13:55,706-__main__-INFO-Running PyArxiv
2015-03-03 08:54:25,889-__main__-INFO-Running PyArxiv
2015-03-04 08:32:22,609-__main__-INFO-Running PyArxiv
2015-03-04 08:32:27,414-__main__-ERROR-Download failure
Traceback (most recent call last):
  File "D:\Dropbox\Python\Arxiv downloader\PyArxiv.py", line 44, in <module>
    urllib.request.urlretrieve(url, "D:\\Desktop\\" + title + ".pdf")
  File "C:\Python34\lib\urllib\request.py", line 188, in urlretrieve
    tfp = open(filename, 'wb')
OSError: [Errno 22] Invalid argument: 'D:\\Desktop\\Does the schock wave in a highly ionized non-isothermal plasma really exist ?.pdf'
2015-03-04 08:33:01,859-__main__-INFO-Running PyArxiv
2015-03-04 08:33:36,227-__main__-ERROR-Download failure
Traceback (most recent call last):
  File "D:\Dropbox\Python\Arxiv downloader\PyArxiv.py", line 44, in <module>
    urllib.request.urlretrieve(url, "D:\\Desktop\\" + title + ".pdf")
  File "C:\Python34\lib\urllib\request.py", line 188, in urlretrieve
    tfp = open(filename, 'wb')
OSError: [Errno 22] Invalid argument: 'D:\\Desktop\\Why do mixed quantum-classical methods describe short-time dynamics through conical intersections so well? Analysis of geometric phase effects.pdf'
2015-03-05 09:52:29,365-__main__-INFO-Running PyArxiv
2015-03-05 09:52:55,802-__main__-ERROR-Download failure
Traceback (most recent call last):
  File "D:\Dropbox\Python\Arxiv downloader\PyArxiv.py", line 44, in <module>
    urllib.request.urlretrieve(url, "D:\\Desktop\\" + title + ".pdf")
  File "C:\Python34\lib\urllib\request.py", line 188, in urlretrieve
    tfp = open(filename, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Desktop\\Yield estimation of neutron-rich rare isotopes induced by 200 MeV/u ^{132}Sn beams by using GEANT4.pdf'
2015-03-05 16:31:50,968-__main__-INFO-Running PyArxiv
2015-03-05 17:06:11,570-__main__-INFO-Running PyArxiv
2015-03-06 10:54:56,698-__main__-INFO-Running PyArxiv
2015-03-10 10:21:55,116-__main__-INFO-Running PyArxiv
2015-03-11 08:04:13,978-__main__-INFO-Running PyArxiv
2015-03-16 06:54:43,430-__main__-INFO-Running PyArxiv
2015-03-17 10:36:36,870-__main__-INFO-Running PyArxiv
2015-03-17 10:37:22,717-__main__-ERROR-Download failure
Traceback (most recent call last):
  File "D:\Dropbox\Python\Arxiv downloader\PyArxiv.py", line 44, in <module>
    urllib.request.urlretrieve(url, "D:\\Desktop\\Arxiv\\" + title + ".pdf")
  File "C:\Python34\lib\urllib\request.py", line 188, in urlretrieve
    tfp = open(filename, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Desktop\\Arxiv\\Backward-propagating MeV electrons from 10^{18} W/cm^2 laser interactions with water.pdf'
2015-03-17 10:37:45,066-__main__-INFO-Running PyArxiv
2015-03-17 10:37:48,338-__main__-INFO-Running PyArxiv
2015-03-17 10:38:06,644-__main__-INFO-Running PyArxiv
2015-03-17 10:39:16,792-__main__-INFO-Running PyArxiv
2015-03-18 07:57:23,517-__main__-INFO-Running PyArxiv
2015-03-20 06:56:26,402-__main__-INFO-Running PyArxiv
2015-03-23 06:51:01,777-__main__-INFO-Running PyArxiv
2015-03-24 07:56:54,469-__main__-INFO-Running PyArxiv
2015-03-27 07:12:12,458-__main__-INFO-Running PyArxiv
